---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: gradle-remote-cache
    namespace: gradle-remote-cache
    labels:
        app: gradle-remote-cache
        service: gradle-remote-cache
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: gradle-remote-cache
                service: gradle-remote-cache
        spec:
            volumes:
                -   name: node-config
                    emptyDir: { }
            initContainers:
                -   name: create-config
                    image: busybox:1.33.1
                    # Scheme: https://docs.gradle.com/build-cache-node/schema/build-cache-node-config-schema-2.json
                    command: [ 'sh','-c','mkdir -p /data/conf; printf "%s\n" "version: 2" "cache:" "  targetSize: 500000" "  maxArtifactSize: 200" "  credentials:" "    anonymousLevel: \"READWRITE\"" "    users: []" > /data/conf/config.yaml' ]
                    volumeMounts:
                        -   name: node-config
                            mountPath: /data
            containers:
                -   name: gradle-remote-cache
                    image: NODE_IMAGE
                    imagePullPolicy: IfNotPresent
                    resources:
                        requests:
                            memory: 6Gi
                            cpu: 1
                        limits:
                            memory: 12Gi
                            cpu: 2
                    ports:
                        -   containerPort: 5071
                    env:
                        -   name: JAVA_OPTS
                            value: "-Xms3g -Xmx10g -XX:MaxDirectMemorySize=1g"
                    volumeMounts:
                        -   name: node-config
                            mountPath: /data
            tolerations:
                -   key: dedicated
                    operator: Equal
                    value: android
                    effect: NoSchedule
---
kind: Service
apiVersion: v1
metadata:
    name: gradle-remote-cache
    namespace: gradle-remote-cache
    labels:
        name: gradle-remote-cache
        service: gradle-remote-cache
spec:
    selector:
        app: gradle-remote-cache
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 5071
---
kind: Ingress
apiVersion: apps/v1
metadata:
    name: gradle-remote-cache
    namespace: gradle-remote-cache
    annotations:
        kubernetes.io/ingress.class: service
        ingress.kubernetes.io/proxy-body-size: 200m
        nginx.ingress.kubernetes.io/proxy-body-size: 200m
        nginx.org/client-max-body-size: 200m
spec:
    rules:
        -   host: "GRADLE_CACHE_NODE_HOST"
            http:
                paths:
                    -   path: "/"
                        backend:
                            serviceName: gradle-remote-cache
                            servicePort: 80
